version: "3.8"

services:
  mongodb:
    image: mongo:4.2.16-bionic
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
